### ISSUE TITLE
License file is missing from pipy download - please tag your releases here

### ISSUE THREAD

**Issue by tillea** [wdecoster/nanomath#15]
Hi,
I intend to package nanomath for Debian. Usually I prefer to package tagged releases from github since I frequently observed that downloads on pipy are incomplete. Unfortunately here on Github you do not have any tags while pipy has at least 0.23.1. I'd consider it good style to tag your releases here as well.
The problem becomes obvious when checking the pipy tarball where the LICENSE file is missing. This would be hard to accept for Debian since every software needs a license.
Could you please make sure that the pipy download is complete - or even more preferably could you tag your releases here.
BTW, besides a LICENSE a copyright is missing and I just have to wild guess that the owner of this Github project - Wouter De Coster - is the only copyright holder. Please also specify this.
Thanks a lot, Andreas.

**Comment by wdecoster** [comment]
Hi Andreas,

Thanks for the suggestions, I'll take care of the LICENSE and tagged releases. What is the recommended way to indicate the copyright holder?

Cheers,
Wouter

**Comment by tillea** [comment]
Hi Wouter,

On Sat, Apr 25, 2020 at 01:35:30AM -0700, Wouter De Coster wrote:
> Thanks for the suggestions, I'll take care of the LICENSE and tagged releases.
:-)

> What is the recommended way to indicate the copyright holder?
I'm using
  Copyright: 2016-2020 Wouter De Coster <decosterwouter@gmail.com>
in the Debian copyright file.  You might like to add this to the
LICENSE file or README* (some people say it should be in every file
but I think the easy way is sufficient.
Kind regards, Andreas.

**Comment by wdecoster** [comment]
Please see https://github.com/wdecoster/nanomath/releases/tag/0.23.2 for the release

**Comment by smoe** [comment]
https://github.com/wdecoster/nanomath/releases/tag/1.0.1 ?

**Comment by wdecoster** [comment]
Thanks for the reminder -> that release exists now!
